"""
evaluate.py — Evaluation Script
Part 3 of Webmobi ML Internship Assignment

What this script does:
1. Reads results/predictions.csv (generated by inference.py)
2. Computes WER, CER, average latency, sample count
3. Saves results/metrics.json
4. Saves results/report.md
"""

import os
import csv
import json
from jiwer import wer, cer

# ── Config ───────────────────────────────────────────────────────────────────

PREDICTIONS_FILE = "results/predictions.csv"
METRICS_FILE     = "results/metrics.json"
REPORT_FILE      = "results/report.md"


def load_predictions(filepath):
    """
    Load predictions CSV.
    Returns list of dicts with audio_id, ground_truth, prediction, latency_sec.
    """
    rows = []
    with open(filepath, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    print(f"Loaded {len(rows)} predictions from {filepath}")
    return rows


def compute_metrics(rows):
    """
    Compute all evaluation metrics.

    WER (Word Error Rate):
      How many words were wrong as a fraction of total words.
      Example: GT = "HELLO WORLD", PRED = "HELLO WORD"
               1 word wrong out of 2 → WER = 0.5 = 50%
      Lower is better. 0% = perfect.

    CER (Character Error Rate):
      Same idea but at character level.
      More granular than WER.

    Latency:
      How many seconds the model took per audio clip on average.
    """

    ground_truths = [row["ground_truth"] for row in rows]
    predictions   = [row["prediction"]   for row in rows]
    latencies     = [float(row["latency_sec"]) for row in rows]

    # jiwer computes WER and CER across the full list at once
    overall_wer = round(wer(ground_truths, predictions), 4)
    overall_cer = round(cer(ground_truths, predictions), 4)

    avg_latency = round(sum(latencies) / len(latencies), 3)
    min_latency = round(min(latencies), 3)
    max_latency = round(max(latencies), 3)
    total_time  = round(sum(latencies), 3)

    metrics = {
        "model"              : "openai/whisper-small",
        "dataset"            : "librispeech_asr (test-clean)",
        "num_samples"        : len(rows),
        "wer"                : overall_wer,
        "wer_percent"        : f"{overall_wer * 100:.2f}%",
        "cer"                : overall_cer,
        "cer_percent"        : f"{overall_cer * 100:.2f}%",
        "avg_latency_sec"    : avg_latency,
        "min_latency_sec"    : min_latency,
        "max_latency_sec"    : max_latency,
        "total_inference_sec": total_time,
    }

    return metrics


def save_metrics(metrics):
    """Save metrics to results/metrics.json"""
    os.makedirs("results", exist_ok=True)
    with open(METRICS_FILE, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)
    print(f"Metrics saved to {METRICS_FILE}")


def save_report(metrics, rows):
    """
    Save a human-readable markdown report to results/report.md
    Includes summary stats and a sample predictions table.
    """
    os.makedirs("results", exist_ok=True)

    lines = []
    lines.append("# Whisper Evaluation Report")
    lines.append("")
    lines.append("## Model & Dataset")
    lines.append(f"- **Model:** {metrics['model']}")
    lines.append(f"- **Dataset:** {metrics['dataset']}")
    lines.append(f"- **Samples evaluated:** {metrics['num_samples']}")
    lines.append("")

    lines.append("## Summary Metrics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Word Error Rate (WER) | {metrics['wer_percent']} |")
    lines.append(f"| Character Error Rate (CER) | {metrics['cer_percent']} |")
    lines.append(f"| Average Inference Latency | {metrics['avg_latency_sec']}s |")
    lines.append(f"| Min Latency | {metrics['min_latency_sec']}s |")
    lines.append(f"| Max Latency | {metrics['max_latency_sec']}s |")
    lines.append(f"| Total Inference Time | {metrics['total_inference_sec']}s |")
    lines.append("")

    lines.append("## What These Numbers Mean")
    lines.append("")
    lines.append(
        "**WER** measures the fraction of words that were wrong. "
        "A WER of 5% means 5 out of every 100 words were incorrect. "
        "Whisper-small typically achieves 3-5% WER on LibriSpeech test-clean, "
        "which is considered excellent for a small model running on CPU."
    )
    lines.append("")
    lines.append(
        "**CER** is more granular — it measures character-level errors. "
        "It is always lower than or equal to WER since partial word errors "
        "count less at the character level."
    )
    lines.append("")
    lines.append(
        "**Latency** is measured per sample. On CPU, whisper-small typically "
        "takes 2-8 seconds per clip depending on audio length. On GPU it would "
        "be under 1 second."
    )
    lines.append("")

    lines.append("## Sample Predictions (first 10)")
    lines.append("")
    lines.append("| ID | Ground Truth | Prediction |")
    lines.append("|---|---|---|")
    for row in rows[:10]:
        gt   = row["ground_truth"][:60]
        pred = row["prediction"][:60]
        lines.append(f"| {row['audio_id']} | {gt} | {pred} |")
    lines.append("")

    lines.append("## Limitations")
    lines.append("")
    lines.append("- Evaluated on clean read-speech (LibriSpeech) — real-world noisy audio would likely show higher WER.")
    lines.append("- Inference was run on CPU — latency would be ~5-10x faster on GPU.")
    lines.append("- whisper-small is not the most accurate Whisper variant; whisper-large-v3 achieves lower WER.")
    lines.append("- 20 samples is a small evaluation set — results may not fully represent model performance.")

    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Report saved to {REPORT_FILE}")


def print_summary(metrics):
    """Print a clean summary table to terminal."""
    print("\n" + "=" * 60)
    print("  EVALUATION RESULTS")
    print("=" * 60)
    print(f"  Model          : {metrics['model']}")
    print(f"  Samples        : {metrics['num_samples']}")
    print(f"  WER            : {metrics['wer_percent']}")
    print(f"  CER            : {metrics['cer_percent']}")
    print(f"  Avg Latency    : {metrics['avg_latency_sec']}s")
    print(f"  Total Time     : {metrics['total_inference_sec']}s")
    print("=" * 60)


def run():
    """Main function — runs the full evaluation pipeline."""
    print("=" * 60)
    print("  WHISPER EVALUATION PIPELINE")
    print("=" * 60)

    if not os.path.exists(PREDICTIONS_FILE):
        print(f"Error: {PREDICTIONS_FILE} not found.")
        print("Please run inference.py first.")
        return

    rows    = load_predictions(PREDICTIONS_FILE)
    metrics = compute_metrics(rows)

    save_metrics(metrics)
    save_report(metrics, rows)
    print_summary(metrics)

    print("\nEvaluation complete.")
    print(f"  metrics.json → {METRICS_FILE}")
    print(f"  report.md    → {REPORT_FILE}")

    return metrics


if __name__ == "__main__":
    run()